LibraryCarpentry/lc-data-intro

index.md

Lessons are specific, having general information about how to participate in Library Carpentry doesn't belong at this level (i think!)
Please delete the text below before submitting your contribution. 
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about …

Removed info about library carpentry in general

---

_episodes/04-regular-expressions.md
_episodes/Regex_exercise
data/swcCoC.md

Added an exercise using www.regex101.com so that learners can practice with a regex tool.
I've also accidentally added a file Regex_exercise which is extraneous and will need to be deleted after we merge (I can't seem to delete it here?)

Added exercise

---

_episodes/03-foundations.md

Made some readability revisions to the first section

---

_episodes/03-foundations.md

- Revised the "why automate?" section for improved clarity

More language updates

---

_episodes/04-regular-expressions.md

Same as https://github.com/LibraryCarpentry/lc-shell/pull/9 ;-)

Hyperlink DOIs against preferred resolver

---

_episodes/03-foundations.md

Changed keyboard shortcuts to table

---

_episodes/03-foundations.md

Removing note to trainer 

---

_episodes/02-jargon-busting.md

Also corrected a spelling error. Think it will need a preface ultimately.

formatting jargon busting as challenge

---

_episodes/03-foundations.md

Updated "Geeks and repetitive tasks" Andy Kirk image with Jon Udell's "Another way to think about geeks and repetitive tasks" image based on https://github.com/LibraryCarpentry/lc-data-intro/issues/38

Added Udell image for repetitive tasks

---

_episodes/03-foundations.md

Reverts LibraryCarpentry/lc-data-intro#43

Revert "Added Udell image for repetitive tasks"

---

_episodes/04-regular-expressions.md

Adding an exercise to extract a substring from one column into another using gsheets and REGEXEXTRACT function. Putting the exercise at the bottom above the `References` (should we move these)?

adding exercise to extract substring in gsheets

---

_episodes/04-regular-expressions.md

See https://github.com/LibraryCarpentry/lc-data-intro/issues/53

Remove 'can you guess' from questions

---

_episodes/03-foundations.md

See https://github.com/LibraryCarpentry/lc-data-intro/issues/38

Replace geek comic

---

_includes/lc/syllabus.html

See diff. Same as https://github.com/LibraryCarpentry/lc-shell/pull/29 ;-)

Update LC lesson links

---

CONTRIBUTING.md

https://github.com/swcarpentry/git-novice/commit/ae4a6939c6622f29a15dc642e55f6602807e1c5d

change language around "main" repository

---

_episodes/04-regular-expressions.md

This follows on from https://github.com/LibraryCarpentry/lc-data-intro/pull/81

Additional changes to 'email' regex exercise (see ref)

---

_episodes/04-regular-expressions.md

Changed the position of a comma.

fixed the structure of the text in one place

---

_episodes/04-regular-expressions.md
data/swcCoC.md

….md)
This reverts commit 01e16812666b1f174e7f486a65e3cfb5565f3e19.
This fixes dead link in _episodes/04-regular_expressions.md and should fix #104

Fixing several broken links in 04-regular-expressions

---

_extras/guide.md

Some instructors do not use Etherpads, use the generic collaborative document instead

Change Etherpad to collaborative document

---

_extras/guide.md

I attempted to better format the guide according to the [Carpentries Style Guide](https://docs.carpentries.org/topic_folders/communications/style-guide.html). Addresses #94

Changed guide to reflect Carpentries style guide.

---

CITATION
README.md

adding DOI badge and updating citation info

Updating DOI and Citation Info

---

_episodes/02-jargon-busting.md

- remove "perhaps"
- add "(or depending on the amount of time available for the exercise, skip to forming groups of 4-6)"
- replace" the terms your groups resolves" w/ "the terms your groups were able to explain"
- add busting tips section

Add jargon busting tips section

---

_episodes/07-quiz.md

- Merge multiple choice quiz questions and answers
- Use Carpentries challenge & solution format

Create quiz episode

---

_episodes/08-exercises.md

- Extract exercises from quiz answers episode and create new episode
- Use Carpentries challenge & solution format

Create exercises episode

---

_episodes/04-regular-expressions.md

Adding a new exercise file to support the final exercise as per https://github.com/LibraryCarpentry/lc-data-intro/issues/110

updating the final exercise

---

_episodes/02-jargon-busting.md

Updating to conform to [The Carpentries Style Guide] (https://docs.carpentries.org/topic_folders/communications/resources/style-guide.html)
Writing out those numbers doesn't seem right to me, but so says The Guide...
as per https://github.com/LibraryCarpentry/lc-data-intro/issues/96

Updating to conform to The Carpentries Style Guide

---

_episodes/04-regular-expressions.md

Updating to conform to [The Carpentries Style Guide] (https://docs.carpentries.org/topic_folders/communications/resources/style-guide.html)
as per https://github.com/LibraryCarpentry/lc-data-intro/issues/99

Updating to conform to Carpentries Style Guide

---

_episodes/07-quiz.md

Minor tweaks to confirm conformance to Carpentries Style Guide

checking against Carpentries Style Guide

---

_episodes/10-file-naming.md

- Update header title, questions, objectives, key points
- Add names matter section
- Add challenge to Markdown section

Create new file naming and formatting episode

---

_episodes/02-match-extract-strings.md

Create callout with heading based on https://github.com/LibraryCarpentry/lc-data-intro/issues/152

Create callout using regular expressions

---

_episodes/01-regular-expressions.md

Addresses issue https://github.com/LibraryCarpentry/lc-data-intro/issues/163
Thanks to @PhilReedData

Improved description of string

---

index.md

Removed misspelled and redundant word "aditional"

---

_config.yml

Setting lifecycle information to the `_config.yml` info and setting it to stable.

adding lifecycle stable to _config.yml

---

_episodes/02-match-extract-strings.md

Per #102, added text suggested by @Libraryan-prog regarding Regex101.com, in order to provide additional context for novice learners.

Improved description for lesson tool.

---

_episodes/01-regular-expressions.md

Noted while preparing to teach the lesson

Proposed correction to typo in episode 1 link to regexper.com

---

_episodes/01-regular-expressions.md

For increased accessibility, see https://github.com/carpentries/carpentries.org/issues/993

Replace negative contractions "xn't with "x not"

---

_episodes/02-match-extract-strings.md

accessibility improvements recommended in [https://github.com/carpentries/carpentries.org/issues/993](https://github.com/carpentries/carpentries.org/issues/993)

Removed contractions

---

_episodes/01-regular-expressions.md

This sentence refers to a website that does not seem to exist anymore: "Some real-world use cases for regex are included on an [ACRL Tech Connect blog](https://acrl.ala.org/techconnect/post/fear-no-longer-regular-expressions/) ."

Remove sentence.

---

_episodes/01-regular-expressions.md

Making the challenge headings monospace will help learners recognise it as code and will help me with the lesson transition: https://github.com/carpentries/lesson-transition/issues/60

make challenge headings monospace

---

episodes/01-regular-expressions.md

Fixes the display of the [exercise heading in episode 1](https://librarycarpentry.org/lc-data-intro/01-regular-expressions.html#rgani.ew).

Fix exercise title in episode 1

---

episodes/01-regular-expressions.md

In the exercise "Taking Capitalization into Consideration" the solution says that the word "community" is found in the text 16 times. This isn't correct, as some of these matches are to "communication", "communications", etc. This PR fixes the solution to match the exercise.

Correct solution to exercise

---

learners/discuss.md

_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
_If any relevant discussions have taken place elsewhere, please provide links to these._
<details>
For more guidance on how to contribute changes to a Carpentries project, please review [the Contributing Guide](CONTRIBUTING.md) and [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html).
Please keep in mind that lesson Maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and …

Update online communities. 

---

index.md

_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
_If any relevant discussions have taken place elsewhere, please provide links to these._
<details>
For more guidance on how to contribute changes to a Carpentries project, please review [the Contributing Guide](CONTRIBUTING.md) and [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html).
Please keep in mind that lesson Maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and …

Update Index getting started

---

episodes/02-match-extract-strings.md

_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
_If any relevant discussions have taken place elsewhere, please provide links to these._
<details>
For more guidance on how to contribute changes to a Carpentries project, please review [the Contributing Guide](CONTRIBUTING.md) and [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html).
Please keep in mind that lesson Maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and …

Add indication of trailing space for clarification

---

index.md

minor change to reflex the lesson is about regexes

changing description in index

---

README.md

changing lesson name in readme

---

config.yaml

changing name to Introduction to Regular Expressions
